// frontend-react/src/routes/admin/ai-configurations.tsx
import { useMemo, useState } from "react";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";
import DeleteRoundedIcon from "@mui/icons-material/DeleteRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import RadioButtonUncheckedRoundedIcon from "@mui/icons-material/RadioButtonUncheckedRounded";
import SmartToyRoundedIcon from "@mui/icons-material/SmartToyRounded";
import Alert from "@mui/material/Alert";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import Chip from "@mui/material/Chip";
import CircularProgress from "@mui/material/CircularProgress";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import Divider from "@mui/material/Divider";
import FormControlLabel from "@mui/material/FormControlLabel";
import IconButton from "@mui/material/IconButton";
import MenuItem from "@mui/material/MenuItem";
import Stack from "@mui/material/Stack";
import Switch from "@mui/material/Switch";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import { useMutation, useQuery } from "@tanstack/react-query";
import { AppShell } from "@/components/layout/AppShell";
import { useCurrentUser } from "@/features/auth/useCurrentUser";
import {
  activateAiConfiguration,
  createAiConfiguration,
  deleteAiConfiguration,
  fetchAiConfigurations,
  updateAiConfiguration,
  type AiConfigurationResponse,
  type CreateAiConfigurationRequest,
  type UpdateAiConfigurationRequest,
} from "@/features/settings/api";

type AiConfigurationForm = {
  name: string;
  providerType: string;
  apiKey: string;
  projectId: string;
  baseUrl: string;
  defaultModel: string;
  enableImageServices: boolean;
  enableTranscriptionServices: boolean;
};

const providerTypes = [
  { label: "OpenAI", value: "openAi" },
  { label: "Azure OpenAI", value: "azureOpenAi" },
  { label: "Anthropic", value: "anthropic" },
  { label: "Ollama", value: "ollama" },
  { label: "Custom (OpenAI-compatible)", value: "custom" },
];

function defaultForm(): AiConfigurationForm {
  return {
    name: "",
    providerType: "openAi",
    apiKey: "",
    projectId: "",
    baseUrl: "",
    defaultModel: "",
    enableImageServices: true,
    enableTranscriptionServices: true,
  };
}

function subtitleParts(config: AiConfigurationResponse) {
  return [
    config.providerType,
    config.defaultModel,
    config.baseUrl,
    config.maskedApiKey,
  ].filter(Boolean).join(" · ");
}

export function AdminAiConfigurationsRouteComponent() {
  const { data: user } = useCurrentUser();
  const [status, setStatus] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [formDialogOpen, setFormDialogOpen] = useState(false);
  const [editingConfigId, setEditingConfigId] = useState<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<AiConfigurationResponse | null>(null);
  const [form, setForm] = useState<AiConfigurationForm>(defaultForm);
  const query = useQuery({ queryKey: ["admin-ai-configurations"], queryFn: fetchAiConfigurations });
  const createMutation = useMutation({ mutationFn: createAiConfiguration });
  const updateMutation = useMutation({ mutationFn: async ({ id, payload }: { id: string; payload: UpdateAiConfigurationRequest }) => await updateAiConfiguration(id, payload) });
  const deleteMutation = useMutation({ mutationFn: deleteAiConfiguration });
  const activateMutation = useMutation({ mutationFn: activateAiConfiguration });

  const configs = query.data ?? [];
  const dialogTitle = editingConfigId ? "Edit AI provider" : "Add AI provider";
  const isSaving = createMutation.isPending || updateMutation.isPending;

  const deleteTargetName = deleteTarget?.name ?? "this provider";
  const pageDescription = useMemo(
    () => "Manage AI provider configurations and activate the default provider.",
    [],
  );

  async function refresh() {
    await query.refetch();
  }

  function openCreateDialog() {
    setForm(defaultForm());
    setEditingConfigId(null);
    setFormDialogOpen(true);
  }

  function openEditDialog(config: AiConfigurationResponse) {
    setForm({
      name: config.name,
      providerType: config.providerType,
      apiKey: "",
      projectId: config.projectId ?? "",
      baseUrl: config.baseUrl ?? "",
      defaultModel: config.defaultModel ?? "",
      enableImageServices: config.enableImageServices,
      enableTranscriptionServices: config.enableTranscriptionServices,
    });
    setEditingConfigId(config.id);
    setFormDialogOpen(true);
  }

  async function handleSave() {
    setError(null);

    try {
      if (editingConfigId) {
        await updateMutation.mutateAsync({
          id: editingConfigId,
          payload: {
            name: form.name || null,
            apiKey: form.apiKey || null,
            projectId: form.projectId || null,
            baseUrl: form.baseUrl || null,
            defaultModel: form.defaultModel || null,
            enableImageServices: form.enableImageServices,
            enableTranscriptionServices: form.enableTranscriptionServices,
          },
        });
        setStatus("AI provider updated");
      } else {
        const payload: CreateAiConfigurationRequest = {
          name: form.name,
          providerType: form.providerType,
          apiKey: form.apiKey || null,
          projectId: form.projectId || null,
          baseUrl: form.baseUrl || null,
          defaultModel: form.defaultModel || null,
          enableImageServices: form.enableImageServices,
          enableTranscriptionServices: form.enableTranscriptionServices,
        };
        await createMutation.mutateAsync(payload);
        setStatus("AI provider created");
      }

      setFormDialogOpen(false);
      await refresh();
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : "Unable to save AI provider");
    }
  }

  async function handleActivate(id: string) {
    setError(null);

    try {
      await activateMutation.mutateAsync(id);
      setStatus("AI provider activated");
      await refresh();
    } catch (activateError) {
      setError(activateError instanceof Error ? activateError.message : "Unable to activate AI provider");
    }
  }

  async function handleDelete() {
    if (!deleteTarget) return;

    setError(null);

    try {
      await deleteMutation.mutateAsync(deleteTarget.id);
      setStatus("AI provider deleted");
      setDeleteTarget(null);
      await refresh();
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : "Unable to delete AI provider");
    }
  }

  if (!user) {
    return (
      <Box sx={{ display: "grid", placeItems: "center", minHeight: "40vh" }}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <AppShell groupSlug={user.groupSlug} userName={user.fullName} title="AI configurations">
      <Box sx={{ width: "100%", maxWidth: 960, mx: "auto" }}>
        <Stack spacing={3}>
          {status ? <Alert severity="success" onClose={() => setStatus(null)}>{status}</Alert> : null}
          {error ? <Alert severity="error" onClose={() => setError(null)}>{error}</Alert> : null}
          {query.error ? <Alert severity="error">{query.error instanceof Error ? query.error.message : "Unable to load AI configurations"}</Alert> : null}

          <Box sx={{ borderBottom: 1, borderColor: "divider", pb: 2.5 }}>
            <Stack direction={{ xs: "column", sm: "row" }} spacing={2} alignItems={{ sm: "center" }}>
              <SmartToyRoundedIcon color="primary" sx={{ fontSize: 64, flexShrink: 0 }} />
              <Stack spacing={0.5}>
                <Typography variant="h4">AI configurations</Typography>
                <Typography color="text.secondary">
                  {pageDescription}
                </Typography>
              </Stack>
            </Stack>
          </Box>

          <Stack direction="row" justifyContent="flex-end">
            <Button onClick={openCreateDialog} startIcon={<AddRoundedIcon />} variant="contained">
              Add AI provider
            </Button>
          </Stack>

          {query.isLoading ? (
            <Box sx={{ display: "grid", placeItems: "center", minHeight: 240 }}>
              <CircularProgress />
            </Box>
          ) : configs.length ? (
            <Card variant="outlined">
              {configs.map((config, index) => (
                <Box key={config.id}>
                  <Box sx={{ px: { xs: 2, md: 3 }, py: 2.5 }}>
                    <Stack
                      direction={{ xs: "column", md: "row" }}
                      spacing={2}
                      alignItems={{ md: "center" }}
                      justifyContent="space-between"
                    >
                      <Stack direction="row" spacing={2} sx={{ minWidth: 0, flex: 1 }} alignItems="flex-start">
                        {config.isActive ? (
                          <CheckCircleRoundedIcon color="success" sx={{ mt: 0.25 }} />
                        ) : (
                          <RadioButtonUncheckedRoundedIcon color="disabled" sx={{ mt: 0.25 }} />
                        )}
                        <Stack spacing={0.5} sx={{ minWidth: 0 }}>
                          <Typography variant="h6">{config.name}</Typography>
                          <Typography color="text.secondary" variant="body2">
                            {subtitleParts(config)}
                          </Typography>
                        </Stack>
                      </Stack>

                      <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" useFlexGap>
                        {config.isActive ? (
                          <Chip color="success" label="Active" size="small" variant="outlined" />
                        ) : (
                          <Button
                            color="info"
                            onClick={() => void handleActivate(config.id)}
                            size="small"
                            variant="outlined"
                            disabled={activateMutation.isPending}
                          >
                            Set active
                          </Button>
                        )}
                        <IconButton aria-label={`Edit ${config.name}`} onClick={() => openEditDialog(config)} size="small">
                          <EditRoundedIcon />
                        </IconButton>
                        <IconButton aria-label={`Delete ${config.name}`} color="error" onClick={() => setDeleteTarget(config)} size="small">
                          <DeleteRoundedIcon />
                        </IconButton>
                      </Stack>
                    </Stack>
                  </Box>
                  {index < configs.length - 1 ? <Divider /> : null}
                </Box>
              ))}
            </Card>
          ) : (
            <Card variant="outlined">
              <Box sx={{ px: 3, py: 8, textAlign: "center" }}>
                <Typography color="text.secondary">No AI providers configured yet.</Typography>
              </Box>
            </Card>
          )}
        </Stack>
      </Box>

      <Dialog open={formDialogOpen} onClose={() => setFormDialogOpen(false)} fullWidth maxWidth="sm">
        <DialogTitle>{dialogTitle}</DialogTitle>
        <DialogContent>
          <Stack spacing={2} sx={{ pt: 1 }}>
            <TextField
              autoFocus
              label="Name"
              required
              value={form.name}
              onChange={event => setForm(current => ({ ...current, name: event.target.value }))}
            />
            <TextField
              select
              label="Provider type"
              value={form.providerType}
              onChange={event => setForm(current => ({ ...current, providerType: event.target.value }))}
            >
              {providerTypes.map(option => (
                <MenuItem key={option.value} value={option.value}>{option.label}</MenuItem>
              ))}
            </TextField>
            <TextField
              label={editingConfigId ? "API key (leave blank to keep current key)" : "API key"}
              type="password"
              autoComplete="new-password"
              value={form.apiKey}
              onChange={event => setForm(current => ({ ...current, apiKey: event.target.value }))}
            />
            <TextField
              label="Project ID (optional)"
              value={form.projectId}
              onChange={event => setForm(current => ({ ...current, projectId: event.target.value }))}
            />
            <TextField
              label="Base URL (optional)"
              value={form.baseUrl}
              onChange={event => setForm(current => ({ ...current, baseUrl: event.target.value }))}
            />
            <TextField
              label="Default model"
              value={form.defaultModel}
              onChange={event => setForm(current => ({ ...current, defaultModel: event.target.value }))}
            />
            <FormControlLabel
              control={(
                <Switch
                  checked={form.enableImageServices}
                  onChange={(_, checked) => setForm(current => ({ ...current, enableImageServices: checked }))}
                />
              )}
              label="Enable image services"
            />
            <FormControlLabel
              control={(
                <Switch
                  checked={form.enableTranscriptionServices}
                  onChange={(_, checked) => setForm(current => ({ ...current, enableTranscriptionServices: checked }))}
                />
              )}
              label="Enable transcription services"
            />
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setFormDialogOpen(false)}>Cancel</Button>
          <Button onClick={() => void handleSave()} disabled={isSaving || !form.name.trim()} variant="contained">
            Save
          </Button>
        </DialogActions>
      </Dialog>

      <Dialog open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} fullWidth maxWidth="xs">
        <DialogTitle>Delete AI provider</DialogTitle>
        <DialogContent>
          <Typography color="text.secondary" sx={{ pt: 1 }}>
            Delete {deleteTargetName}?
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDeleteTarget(null)}>Cancel</Button>
          <Button color="error" onClick={() => void handleDelete()} disabled={deleteMutation.isPending} variant="contained">
            Delete
          </Button>
        </DialogActions>
      </Dialog>
    </AppShell>
  );
}

// frontend/app/pages/admin/ai-configurations.vue
<template>
  <v-container fluid class="narrow-container">
    <BasePageTitle divider>
      <template #header>
        <v-icon size="80" color="primary">{{ $globals.icons.robot }}</v-icon>
      </template>
      <template #title>
        {{ $t("admin.ai-configurations") }}
      </template>
    </BasePageTitle>

    <!-- Add provider button -->
    <div class="d-flex justify-end mb-4">
      <BaseButton create @click="openCreateDialog">
        {{ $t("admin.add-ai-provider") }}
      </BaseButton>
    </div>

    <!-- Provider list -->
    <v-card v-if="configs.length">
      <template v-for="(config, idx) in configs" :key="config.id">
        <v-list-item :title="config.name" class="py-3">
          <template #prepend>
            <v-icon :color="config.isActive ? 'success' : 'grey'" class="opacity-100 mr-2">
              {{ config.isActive ? $globals.icons.checkboxMarkedCircle : $globals.icons.circle }}
            </v-icon>
          </template>
          <template #subtitle>
            <span class="text-caption">{{ config.providerType }}</span>
            <span v-if="config.defaultModel" class="text-caption ml-2">· {{ config.defaultModel }}</span>
            <span v-if="config.baseUrl" class="text-caption ml-2">· {{ config.baseUrl }}</span>
            <span v-if="config.maskedApiKey" class="text-caption ml-2 font-weight-medium">· {{ config.maskedApiKey }}</span>
          </template>
          <template #append>
            <div class="d-flex align-center" style="gap: 8px">
              <v-chip
                v-if="config.isActive"
                color="success"
                size="small"
                variant="tonal"
              >
                {{ $t("general.active") }}
              </v-chip>
              <BaseButton
                v-else
                size="small"
                color="info"
                secondary
                @click="activateConfig(config.id)"
              >
                {{ $t("admin.set-active") }}
              </BaseButton>
              <v-btn icon size="small" variant="text" @click="openEditDialog(config)">
                <v-icon>{{ $globals.icons.edit }}</v-icon>
              </v-btn>
              <v-btn icon size="small" variant="text" color="error" @click="confirmDelete(config)">
                <v-icon>{{ $globals.icons.delete }}</v-icon>
              </v-btn>
            </div>
          </template>
        </v-list-item>
        <v-divider v-if="idx < configs.length - 1" :key="`div-${config.id}`" />
      </template>
    </v-card>
    <v-card v-else class="text-center pa-8 text-medium-emphasis">
      {{ $t("admin.no-ai-providers") }}
    </v-card>

    <!-- Create / Edit dialog -->
    <BaseDialog
      v-model="dialog.show"
      :title="dialog.editing ? $t('admin.edit-ai-provider') : $t('admin.add-ai-provider')"
      :icon="$globals.icons.robot"
      :can-confirm="true"
      @confirm="saveConfig"
    >
      <v-card-text class="pt-4">
        <v-text-field
          v-model="form.name"
          :label="$t('general.name')"
          variant="outlined"
          class="mb-3"
          required
        />
        <v-select
          v-model="form.providerType"
          :label="$t('admin.provider-type')"
          :items="providerTypes"
          item-title="text"
          item-value="value"
          variant="outlined"
          class="mb-3"
        />
        <v-text-field
          v-model="form.apiKey"
          :label="dialog.editing ? $t('admin.api-key-leave-blank') : $t('admin.api-key')"
          variant="outlined"
          type="password"
          autocomplete="new-password"
          class="mb-3"
        />
        <v-text-field
          v-model="form.projectId"
          :label="$t('admin.project-id-optional')"
          variant="outlined"
          class="mb-3"
        />
        <v-text-field
          v-model="form.baseUrl"
          :label="$t('admin.base-url-optional')"
          variant="outlined"
          class="mb-3"
        />
        <v-text-field
          v-model="form.defaultModel"
          :label="$t('admin.default-model')"
          variant="outlined"
          class="mb-3"
        />
        <v-checkbox
          v-model="form.enableImageServices"
          :label="$t('admin.enable-image-services')"
          color="primary"
          hide-details
        />
        <v-checkbox
          v-model="form.enableTranscriptionServices"
          :label="$t('admin.enable-transcription-services')"
          color="primary"
          hide-details
          class="mb-4"
        />
      </v-card-text>
    </BaseDialog>

    <!-- Delete confirmation -->
    <BaseDialog
      v-model="deleteDialog.show"
      :title="$t('admin.delete-ai-provider')"
      :icon="$globals.icons.alertCircle"
      color="error"
      :can-confirm="true"
      @confirm="deleteConfig"
    >
      <v-card-text>
        {{ $t("admin.delete-ai-provider-confirm", { name: deleteDialog.target?.name }) }}
      </v-card-text>
    </BaseDialog>
  </v-container>
</template>

<script setup lang="ts">
import { useAdminApi } from "~/composables/api";
import { alert } from "~/composables/use-toast";
import { useGlobalI18n } from "~/composables/use-global-i18n";
import type { AiConfigurationResponse } from "~/lib/api/admin/admin-ai-configurations";

definePageMeta({ layout: "admin" });

onMounted(() => { setPageLayout("admin"); });

const { $globals } = useNuxtApp();
const i18n = useGlobalI18n();
const adminApi = useAdminApi();

useSeoMeta({ title: i18n.t("admin.ai-configurations") });

const configs = ref<AiConfigurationResponse[]>([]);
async function loadConfigs() {
  const { data } = await adminApi.aiConfigurations.getAll();
  if (data) configs.value = data;
}

onMounted(loadConfigs);

const providerTypes = [
  { text: "OpenAI", value: "openAi" },
  { text: "Azure OpenAI", value: "azureOpenAi" },
  { text: "Anthropic", value: "anthropic" },
  { text: "Ollama", value: "ollama" },
  { text: "Custom (OpenAI-compatible)", value: "custom" },
];

const defaultForm = () => ({
  name: "",
  providerType: "openAi",
  apiKey: "",
  projectId: "",
  baseUrl: "",
  defaultModel: "",
  enableImageServices: true,
  enableTranscriptionServices: true,
});

const form = reactive(defaultForm());

const dialog = reactive({
  show: false,
  editing: false,
  editingId: "" as string,
});

function openCreateDialog() {
  Object.assign(form, defaultForm());
  dialog.editing = false;
  dialog.editingId = "";
  dialog.show = true;
}

function openEditDialog(config: AiConfigurationResponse) {
  form.name = config.name;
  form.providerType = config.providerType;
  form.apiKey = "";
  form.projectId = config.projectId ?? "";
  form.baseUrl = config.baseUrl ?? "";
  form.defaultModel = config.defaultModel ?? "";
  form.enableImageServices = config.enableImageServices;
  form.enableTranscriptionServices = config.enableTranscriptionServices;
  dialog.editing = true;
  dialog.editingId = config.id;
  dialog.show = true;
}

async function saveConfig() {
  if (dialog.editing) {
    const { error } = await adminApi.aiConfigurations.update(dialog.editingId, {
      name: form.name || null,
      apiKey: form.apiKey || null,
      projectId: form.projectId || null,
      baseUrl: form.baseUrl || null,
      defaultModel: form.defaultModel || null,
      enableImageServices: form.enableImageServices,
      enableTranscriptionServices: form.enableTranscriptionServices,
    });
    if (error) { alert.error(i18n.t("events.something-went-wrong")); return; }
    alert.success(i18n.t("general.item-updated"));
  }
  else {
    const { error } = await adminApi.aiConfigurations.create({
      name: form.name,
      providerType: form.providerType,
      apiKey: form.apiKey || null,
      projectId: form.projectId || null,
      baseUrl: form.baseUrl || null,
      defaultModel: form.defaultModel || null,
      enableImageServices: form.enableImageServices,
      enableTranscriptionServices: form.enableTranscriptionServices,
    });
    if (error) { alert.error(i18n.t("events.something-went-wrong")); return; }
    alert.success(i18n.t("general.item-created"));
  }
  dialog.show = false;
  await loadConfigs();
}

async function activateConfig(id: string) {
  const { error } = await adminApi.aiConfigurations.activate(id);
  if (error) { alert.error(i18n.t("events.something-went-wrong")); return; }
  await loadConfigs();
}

const deleteDialog = reactive({
  show: false,
  target: null as AiConfigurationResponse | null,
});

function confirmDelete(config: AiConfigurationResponse) {
  deleteDialog.target = config;
  deleteDialog.show = true;
}

async function deleteConfig() {
  if (!deleteDialog.target) return;
  const { error } = await adminApi.aiConfigurations.delete(deleteDialog.target.id);
  if (error) { alert.error(i18n.t("events.something-went-wrong")); return; }
  alert.success(i18n.t("general.item-deleted"));
  deleteDialog.show = false;
  await loadConfigs();
}
</script>
